version: '3.4'

services:
  api:
    image: api
    build:
      context: ./Lab0
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - "3000:3000"