name: First Workflow

on:
  push:
    branches:
      - Lab1

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        uses: docker build -t myapp:v1 .

      - name: Stop Container
        run: |
          docker stop myapp:v1 || true
          docker rm myapp:v1
          
      - name: Start Containera
        run:
          docker run -d -p 3000:3000 --name myapp myapp:v1