name: workflow 4

on:
    push:
        branches:
            - Lab3

jobs:
    github:
        runs-on: ubuntu-latest
        steps:
            - name: ChceckOut
              uses: actions/checkout@v4

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v2
              with:
                projectBaseDir: Lab0
              env:
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name : Build Docker Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME}}/myapp:${{ github.sha }} ./Lab0

            - name: Login To Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
         
            - name: Push Docker Image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

    CD:
        runs-on: self-hosted
        needs: github
        steps:
            - name: Pull Docker Image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
  
            - name: Stop Container
              run: docker stop myapp || true

            - name: Start Container
              run: | 
                  docker rm myapp || true
                  docker run -d -p 3000:3000 --name myapp \
                  ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
